version: '3.7'

services:

  db:
    image: postgres:17.4-alpine
    restart: always
    container_name: users-db
    shm_size: '256mb'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"