openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
paths:
  /api/users:
    post:
      summary: Create a new user
      operationId: create
      tags:
        - User
      requestBody:
        description: User creation request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input provided
        '409':
          description: User with the provided email or nickname already exists

components:
  schemas:
    UserCreateRequest:
      type: object
      properties:
        first_name:
          type: string
          example: 'Alice'
        last_name:
          type: string
          example: 'Bob'
        nickname:
          type: string
          example: 'AB123'
        password:
          type: string
          format: password
          example: 'supersecurepassword'
        email:
          type: string
          format: email
          example: 'alice@bob.com'
          x-field-extra-annotation: "@org.hibernate.validator.constraints.Email"
        country:
          type: string
          example: 'UK'
      required:
        - first_name
        - last_name
        - nickname
        - password
        - email
        - country

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 'd2a7924e-765f-4949-bc4c-219c956d0f8b'
        first_name:
          type: string
          example: 'Alice'
        last_name:
          type: string
          example: 'Bob'
        nickname:
          type: string
          example: 'AB123'
        email:
          type: string
          format: email
          example: 'alice@bob.com'
        country:
          type: string
          example: 'UK'
        created_at:
          type: string
          format: date-time
          example: '2019-10-12T07:20:50.52Z'
        updated_at:
          type: string
          format: date-time
          example: '2019-10-12T07:20:50.52Z'
